### ISSUE TITLE
aqui renderizas 

### ISSUE THREAD

**Issue by itsrusty** [tjhoan/Monitorias-Univalle#2]
### pon esto antes de cerrar body

    
    <% if (typeof alerta !=='undefined' ) { %>
    <script>
      Swal.fire({
        icon: "error",
        title: "Error alaburguer",
        text: "<%= alerta %>",
      });
    </script>
    <% } %>``

**Comment by tjhoan** [comment]
> ### pon esto antes de cerrar body
> ```
> 
> <% if (typeof alerta !=='undefined' ) { %>
> <script>
>   Swal.fire({
>     icon: "error",
>     title: "Error alaburguer",
>     text: "<%= alerta %>",
>   });
> </script>
> <% } %>``
> ```
